views:
  category:
    fields:
      cid:
        name: '分类ID'
        sort_type: 'number'
        filter_type: 'number'
      name:
        name: '名称'
        filter_type: 'string'
  page:
    relationship:
      user:
        left:
          field: 'uid'
        right:
          field: 'uid'
    fields:
      pid:
        name: '页面ID'
        sort_type: 'number'
        filter_type: 'number'
      title:
        name: '页面标题'
        filter_type: 'string'
      content:
        name: '页面内容'
      status:
        name: '状态'
        filter_type: 'yes-no'
      uid:
        name: '作者ID'
        sort_type: 'number'
        filter_type: 'number'
      created:
        name: '创建时间'
        sort_type: 'date'
        filter_type: 'number'
      updated:
        name: '更新时间'
        sort_type: 'date'
        filter_type: 'number'
  user:
    fields:
      uid:
        name: '用户ID'
        sort_type: 'number'
        filter_type: 'number'
      username:
        name: '用户名'
        filter_type: 'string'
      email:
        name: '用户邮箱'
        sort_type: 'number'
        filter_type: 'number'
      avatar:
        name: '用户头像'
      status:
        name: '状态'
        filter_type: 'yes-no'
      uid:
        name: '作者ID'
        sort_type: 'number'
        filter_type: 'number'
      created:
        name: '创建时间'
        sort_type: 'date'
        filter_type: 'number'
      updated:
        name: '更新时间'
        sort_type: 'date'
        filter_type: 'number'
      accessed:
        name: '更新时间'
        sort_type: 'date'
        filter_type: 'number'
